services:
  - type: web
    name: copperx-telegram-bot
    env: node
    plan: free
    buildCommand: pnpm install && node build.js
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: BOT_TOKEN
        sync: false
      - key: API_BASE_URL
        value: https://income-api.copperx.io
      - key: PUSHER_APP_KEY
        sync: false
      - key: PUSHER_CLUSTER
        sync: false
      - key: SESSION_SECRET
        sync: false 